### PR TITLE
Code edit exercise

### PR DESCRIPTION
**Pull request by mluen**
Resubmitting pull request to master.

### CODE REVIEW

**Comment by zgeorgii** [comment]
The pull is not supposed to go into my master, please send it to the branch i made you for your edit

**Comment by mluen** [comment]
Paul & Dan did that pull. They both said that's where it's supposed to be
for the exercise tomorrow.

On Thu, Jan 7, 2016 at 5:46 PM, Zach Georgii notifications@github.com
wrote:

> The pull is not supposed to go into my master, please send it to the
> branch i made you for your edit
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zgeorgii/201_day_2_demo/pull/12#issuecomment-169863255
> .

## 

Margaux Luen
919.274.9031 <#UNIQUE_ID_SafeHtmlFilter_>
luen.margaux@gmail.com
http://www.linkedin.com/in/mluen

**Comment by zgeorgii** [comment]
They must have messed up... I can't have that go into my master. we deleted a lottt... my button is gone as well as some links if you check the script.

**Comment by zgeorgii** [comment]
I cleaned up my master script so everything is functional when i got home, idk why they would say that? Sam specifically said in class that we would not be sending out script into the master file of our partner. thats why i sent yours to your wednesday file.

**Comment by mluen** [comment]
Dan doesn't seem to know what's going on. The fact that he isn't in class
doesn't help either. Paul seemed confused when I was asking questions about
GitHub too....

On Thursday, January 7, 2016, Zach Georgii notifications@github.com wrote:

> I cleaned up my master script so everything is functional when i got home,
> idk why they would say that? Sam specifically said in class that we would
> not be sending out script into the master file of our partner. thats why i
> sent yours to your wednesday file.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zgeorgii/201_day_2_demo/pull/12#issuecomment-169888670
> .

## 

Margaux Luen
919.274.9031 <#SafeHtmlFilter_>
luen.margaux@gmail.com
http://www.linkedin.com/in/mluen

**Pull request closed without merging**
